### ISSUE TITLE
Successfully tested in the Livebox 2.1

### ISSUE THREAD

**Issue by danitool** [rvalles/brntool#12]
Hi, the tool was successfully tested on a Arcadyan ARV7519RW22-A-LT (AKA Livebox 2.1).
https://openwrt.org/toh/arcadyan/arv7519

Regards.
Daniel

**Comment by rvalles** [comment]
Grand. To think they send these to people. Awesome.

Back in the day I had a Livebox 2.0. But thankfully we got fibre at some point.

**Comment by rvalles** [comment]
Thanks,
Roc.
