### ISSUE TITLE
Entering Menu fails on ARV752DPW22 EasyBox 803A

### ISSUE THREAD

**Issue by Baumfaust** [rvalles/brntool#4]
Hello good Sir,

I have problems using your brntool for my router ARV752DPW22 EasyBox 803A.
It gets stuck at "waiting for a prompt...". 
After you are sending "   !" in function get2menu you wait for "]"  and ":" to receive.
I wrote a whole block of 1000 chars and that was the result:

`b' \n\r\n\r======================\n\r [#] Set Serial Number\n\r [2] Use Normal Firmware\n\r [3] Use ART-Testing Firmware\n\r [9] Taggle ART Firmware Enable/Disable\n\r [A] Set MAC Address\n\r [B] Set WPA Key\n\r [E] Erase Flash\n\r [G] Run Runtime Code\n\r [H] Set Options\n\r [M] Upload to Memory\n\r [P] Print Boot Params \n\r [R] Read from Memory\n\r [T] Memory Test\n\r [U] Upload to Flash\n\r [V] Set Board Version\n\r [W] Write to Memory\n\r [Y] Go to Memory\n\r [Z] Dump DDR Ram Register\n\r======================\n\r\n\r[DANUBE Boot]: \n\r\n\r======================\n\r [#] Set Serial Number\n\r [2] Use Normal Firmware\n\r [3] Use ART-Testing Firmware\n\r [9] Taggle ART Firmware Enable/Disable\n\r [A] Set MAC Address\n\r [B] Set WPA Key\n\r [E] Erase Flash\n\r [G] Run Runtime Code\n\r [H] Set Options\n\r [M] Upload to Memory\n\r [P] Print Boot Params \n\r [R] Read from Memory\n\r [T] Memory Test\n\r [U] Upload to Flash\n\r [V] Set Board Version\n\r [W] Write to Memory\n\r [Y] Go to Memory\n\r [Z] Dump DDR Ram Register\n\r======================\n\r\n\r[DANUBE Boot]: \n\r\n\r======='`

So reading and writing works, but I guess the Menu is different?

Here you can see the menu as shown when using the tool screen to connect

http://i.imgur.com/8NKhnQo.png

Greetings from Germany

**Comment by rvalles** [comment]
Hello good Sir,

Hm, perhaps try waiting for just ':' that is, remove "ser.read(1)==']' and ", then see if that helps.

The [ and : check done while reading was very ugly in hindsight, and I'd expect it to fail half of the time for devices other than the one I had. (I don't have any danube-booting device in my current residence).

Greetings from Ireland
