### ISSUE TITLE
Firmware images corrupted by UFT8 encoding

### ISSUE THREAD

**Issue by TCM2** [rvalles/brntool#7]
Hi,

the latest version of brntool.py corrupts written images by UTF8 encoding them.

Edit: This is caused by the addition of encode() to fd.write(buf). After noticing the corruption I switched to Python2 and removed the encode() and it worked. I see now that Python3 throws an error without the encode().

Thanks.

**Comment by rvalles** [comment]
Apologies, this one is pretty bad.

It was introduced by merging https://github.com/rvalles/brntool/pull/6

On hindsight, I should have reviewed that pull more carefully.
