### ISSUE TITLE
brntool.py crash - Arcadyan VGV7510KW22 / o2 Box 6431

### ISSUE THREAD

**Issue by ds2k5** [rvalles/brntool#8]
Hi,
unsing Manjaro Linux

python: 3.5.2
python-pyserial: 3.1.1-1
brntool.py from 08/13/2016

connect the Serial Console with minicom

`sudo minicom -b 115200 -D /dev/ttyUSB1`

Power ON the O2 Box 6431 / Arcadyan VGV7510KW22
press multible SPACE

see the Menu:

```
ROM VER: 1.1.4
CFG 01
Tuning DDR begin
DDR Access auto data-eye tuning Rev 0.3a
DDR size from 0xa0000000 - 0xa3ffffff
DDR check ok... start booting...
=======================================================================
Wireless VDSL Gateway VR9 Loader V1.08.02 build Mar 12 2014 14:36:08
                    Arcadyan Technology Corporation
=======================================================================
BSP_RCU_RST_STAT : 70240000
Global GPHY0 GPHY1 reset ...
MXIC MX29GL128EL top boot 16-bit mode found

Copying boot params.....DONE

Press Space Bar 3 times to enter command mode ...123
Yes, Enter command mode ...
[VR9 Boot]:
```

then exit minicom with CNRTL+A Z q

run brntool.py

`sudo ./brntool.py --serial=/dev/ttyUSB1 --read=boot.brntool_dump --addr=0xB0000000 --verbose --size=0x40000`

got this:

Waiting for a prompt...
Ok.
Traceback (most recent call last):
  File "./brntool.py", line 94, in <module>
    main()
  File "./brntool.py", line 91, in main
    memread(ser,options.read,int(options.addr,0),int(options.size,0),options.verbose)
  File "./brntool.py", line 68, in memread
    memreadblock2file(ser,fd,addr,bs)
  File "./brntool.py", line 52, in memreadblock2file
    buf=memreadblock(ser,addr,size)
  File "./brntool.py", line 45, in memreadblock
    buf+=bytes(m.group(1)[1:].split(' '))
TypeError: 'str' object cannot be interpreted as an integer

**What did i wrong ?**
Thanks

**Comment by rvalles** [comment]
I sadly haven't had access to the hardware to test for a while, so I haven't been able to do much testing.

Try passing addr and size as decimal, rather than hex. Let me know if it helps.

**Comment by ds2k5** [comment]
thanks, did you mean like this ?

`sudo ./brntool.py --serial=/dev/ttyUSB1 --read=boot.brntool_dump --addr=2952790016 --verbose --size=262144`

Waiting for a prompt...
Ok.
Traceback (most recent call last):
  File "./brntool.py", line 94, in <module>
    main()
  File "./brntool.py", line 91, in main
    memread(ser,options.read,int(options.addr,0),int(options.size,0),options.verbose)
  File "./brntool.py", line 68, in memread
    memreadblock2file(ser,fd,addr,bs)
  File "./brntool.py", line 52, in memreadblock2file
    buf=memreadblock(ser,addr,size)
  File "./brntool.py", line 45, in memreadblock
    buf+=bytes(m.group(1)[1:].split(' '))
TypeError: 'str' object cannot be interpreted as an integer

**Comment by rvalles** [comment]
OK great.

Can you dump a small block at that address manually? I do guess (via regexp) what a dump was supposed to look like, but don't really remember it myself.

Also, you should try Python2 if you can do that easily. I might have broken Python3 at some point.

**Comment by ds2k5** [comment]
> Also, you should try Python2 if you can do that easily.

wow thats it:
`sudo python2 brntool.py --serial=/dev/ttyUSB1 --read=boot.brntool_dump --addr=0xB0000000 --verbose --size=0x40000`

Addr: 0xb0002710
Size: 252144
Addr: 0xb0004e20
Size: 242144
....

**Thanks a lot!**

**Comment by rvalles** [comment]
Great news. Now I should look into why running with Python3 is broken.
